language: ruby
rvm:
- 2.3.1
before_script:
- chmod +x ./script/cibuild.sh
- chmod +x ./script/deploy.sh
script: "./script/cibuild.sh"
after_success: "./script/deploy.sh"
branches:
  only:
  - source
env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
  - secure: XaxJfr3MZhdYswQ148cKRHz0hfB6Pohy7+hQOcC+s2RHIpaNv6gzS2ZtbVJubfMVYvOHL+1mYHW8o2zAIHgrwoz+sUXVXF/6MesVKWnaQAT8qk7sBr0WYAdeAYjDrPZWRoY1tt2awWRwJwb+OPPkAFGrAxYsVMl+xK5J0AwcuymupZJKoMOIpDWx8RVoWBGH7/fESFvC7MN9TCkR0n0nKynOL6LljzsnJ0zcgKRI+1T21GPXrNfkTcYldGcy1cWIYKjejzzK7GbnSzXh/aUbbxoEcWJCVOzAXbagj6hpNHWcZc2ytF2xnyCzaCS0sZbl3coYZGnbyHFuZbiLU53/PoNBu7GdCB8vnRbd/cDgL6qAAqcxBcoyi+M1aV5YIlmpoNqkDYU9P5AQ3+IG+wFkG6JaWuypTHZpqXUKn9p6GagUuHOgdNDHpapa44Yg0THB/QV7r/sbdAlKRvNFkHy3znGBmUI56mmm3OE/umRYxAv03jxqDkS6s3AiV9BIXlYI04ssW2k/ueqbwY/AsCPknNChs1ATSyh4YHoyXtB1kdFwbxIgMbLf5yTqGkoCaBQZ5p3RxaGvdE2Iea4tJ3rLhGNY739pFwuBOqJQE7ASJceb2hyz4/UrMH4zMT1IRYEyGOorswZD/tEmSjL+POA4Jt992UoQ3JrPilUsx1P1JZc=
sudo: false
