# Setup
title:               PapaScott
tagline:             "I don't claim to succeed at all this!"
description:         '<a href="/">PapaScott</a> is a personal weblog by Scott Hanson.'
descriptiontext:    'A personal weblog by Scott Hanson'
url:                 http://www.papascott.de
baseurl:            ''
permalink:           archives/:year/:month/:day/:title/
comments:            true
# About/contact
author:
  name:              Scott Hanson
  url:               https://twitter.com/papascott
  email:             papascott@gmail.com


## Directories not to rebuild automatically
exclude: [vendor, s3_website.yml, Rakefile, LICENSE.md, README.md, script, Gemfile, Gemfile.lock]

## Do not re-render old posts
# exclude: [vendor, s3_website.yml, Rakefile, LICENSE.md, README.md, _posts/older]
# keep_files: [archives/1999, archives/200, archives/2010, archives/2011, archives/2012, archives/2013, archives/2014, archives/2015]

plugins:
  - jemoji
  - jekyll-archives
  - jekyll-redirect-from
  # - jekyll-admin

jekyll-archives:
  enabled: [year, month]
  permalinks:
    year: '/archives/:year/'
    month: '/archives/:year/:month/'
    #day: '/:year/:month/:day/'
    #tag: '/tag/:name/'
    #category: '/category/:name/'
  layouts:
    year: year-archive
    month: month-archive
    #day: day-archive
    #tag: tag-archive-layout

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts" # previously `post` in Jekyll 2.2.
    values:
      comments: "yes"
