# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
#permalink:           pretty
permalink:           archives/:year/:month/:day/:title/
relative_permalinks: true

#markdown:    rdiscount

# Setup
title:               PapaScott
tagline:             'And you know what they said? Well, some of it was true!'
description:         '<a href="/">PapaScott</a> is a personal weblog by Scott Hanson.'
url:                 http://www.papascott.de
baseurl:            '' 
paginate:            5
comments:            true
# About/contact
author:
  name:              Scott Hanson
  url:               https://twitter.com/papascott
  email:             papascott@gmail.com

## Directories not to rebuild automatically
#exclude: [wordpress]
#keep_files: [wordpress]


# Custom vars
#version:             1.0.0

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts" # previously `post` in Jekyll 2.2.
    values:
      comments: "yes"
